package ua.millfreedom.rom2.text;

// Generated by tools/generate_text_tables.py.
// Source of truth: Main.loadTextFiles() and the configured source files for BuildingText.
// Do not edit manually.

/**
 * Generated table-local mapping for g_building loaded from main/text/building.txt.
 */
public enum BuildingText implements TextTableLocalEntry {
    GOBLIN_HUT_0(0), // "Goblin Hut"
    GOBLIN_HUT_1(1), // "Goblin Hut"
    ORC_HOUSE_2(2), // "Orc House"
    ORC_HOUSE_3(3), // "Orc House"
    WINDMILL_4(4), // "Windmill"
    WINDMILL_5(5), // "Windmill"
    WINDMILL_6(6), // "Windmill"
    WELL_7(7), // "Well"
    HUMAN_HOUSE_8(8), // "Human House"
    HUMAN_HOUSE_9(9), // "Human House"
    CHURCH_10(10), // "Church"
    TOWER_11(11), // "Tower"
    TOWER_12(12), // "Tower"
    CAVE_13(13), // "Cave"
    MAGIC_WELL_14(14), // "Magic Well"
    MAGIC_WELL_15(15), // "Magic Well"
    HUMAN_HOUSE_16(16), // "Human House"
    HUMAN_HOUSE_17(17), // "Human House"
    HUMAN_HOUSE_18(18), // "Human House"
    HUMAN_HOUSE_19(19), // "Human House"
    OGRE_HOUSE_20(20), // "Ogre House"
    OGRE_HOUSE_21(21), // "Ogre House"
    OGRE_HOUSE_22(22), // "Ogre House"
    BEE_HOUSE_23(23), // "Bee House"
    BEE_HOUSE_24(24), // "Bee House"
    SNAKE_HOUSE_25(25), // "Snake House"
    MAGIC_SYMBOL_26(26), // "Magic Symbol"
    SWITCH_27(27), // "Switch"
    SWITCH_28(28), // "Switch"
    RUINS_29(29), // "Ruins"
    RUINS_30(30), // "Ruins"
    RUINS_31(31), // "Ruins"
    BRIDGE_32(32), // "Bridge"
    SHOP_33(33), // "Shop"
    SHOP_34(34), // "Shop"
    HANGING_PEASANT_35(35), // "Hanging Peasant"
    BRIDGE_36(36), // "Bridge"
    BRIDGE_37(37), // "Bridge"
    GRAVE_38(38), // "Grave"
    GRAVE_39(39), // "Grave"
    GRAVE_40(40), // "Grave"
    GRAVE_41(41), // "Grave"
    INN_42(42), // "Inn"
    INN_43(43), // "Inn"
    INN_44(44), // "Inn"
    GUARD_TOWER_45(45), // "Guard Tower"
    GUARD_TOWER_46(46), // "Guard Tower"
    TELEPORT_PAD_47(47), // "Teleport Pad"
    TRAINING_SCHOOL_48(48), // "Training School"
    TRAINING_SCHOOL_49(49), // "Training School"
    TRAINING_SCHOOL_50(50), // "Training School"
    BRIDGE_51(51), // "Bridge"
    CAMPFIRE_52(52), // "Campfire"
    SKRAKAN_S_TOWER_53(53), // "Skrakan's tower"
    SKRAKAN_S_TOWER_54(54), // "Skrakan's tower"
    MAGE_S_TOWER_55(55), // "Mage's tower"
    CASTLE_56(56), // "Castle"
    SPHINX_57(57), // "Sphinx"
    SPHINX_58(58), // "Sphinx"
    SPHINX_59(59), // "Sphinx"
    SPHINX_60(60), // "Sphinx"
    SPHINX_61(61), // "Sphinx"
    SPHINX_62(62), // "Sphinx"
    SPHINX_63(63), // "Sphinx"
    SPHINX_64(64), // "Sphinx"
    CHURCH_65(65), // "Church"
    INN_66(66), // "Inn"
    INN_67(67), // "Inn"
    INN_68(68), // "Inn"
    ROAD_SIGN_69(69), // "Road Sign"
    ROAD_SIGN_70(70), // "Road Sign"
    ROAD_SIGN_71(71), // "Road Sign"
    ROAD_SIGN_72(72), // "Road Sign"
    ROAD_SIGN_73(73), // "Road Sign"
    ROAD_SIGN_74(74), // "Road Sign"
    ALTAR_75(75), // "Altar"
    ALTAR_76(76), // "Altar"
    HOUSE_77(77), // "House"
    HOUSE_78(78), // "House"
    HOUSE_79(79), // "House"
    SHED_80(80), // "Shed"
    SHED_81(81), // "Shed"
    SHED_82(82), // "Shed"
    SHAMAN_S_HOUSE_83(83), // "Shaman's House"
    SHAMAN_S_HOUSE_84(84), // "Shaman's House"
    SHAMAN_S_HOUSE_85(85), // "Shaman's House"
    HOUSE_86(86), // "House"
    HOUSE_87(87), // "House"
    HOUSE_88(88), // "House"
    SHOP_89(89), // "Shop"
    SHOP_90(90), // "Shop"
    SHOP_91(91), // "Shop"
    SHOP_92(92), // "Shop"
    SHOP_93(93), // "Shop"
    SHOP_94(94), // "Shop"
    INN_95(95), // "Inn"
    INN_96(96), // "Inn"
    INN_97(97), // "Inn"
    INN_98(98), // "Inn"
    INN_99(99), // "Inn"
    INN_100(100), // "Inn"
    SHOP_101(101), // "Shop"
    SHOP_102(102), // "Shop"
    SHOP_103(103), // "Shop"
    SHOP_104(104), // "Shop"
    SHOP_105(105), // "Shop"
    SHOP_106(106), // "Shop"
    INN_107(107), // "Inn"
    INN_108(108), // "Inn"
    INN_109(109), // "Inn"
    INN_110(110), // "Inn"
    INN_111(111), // "Inn"
    INN_112(112), // "Inn"
    HOUSE_113(113), // "House"
    HOUSE_114(114), // "House"
    HOUSE_115(115), // "House"
    CRATER_116(116), // "Crater"
    TEPEE_117(117), // "Tepee"
    TEPEE_118(118), // "Tepee"
    TEPEE_119(119), // "Tepee"
    GRAVE_120(120), // "Grave"
    GRAVE_121(121), // "Grave"
    GRAVE_122(122), // "Grave"
    TENT_123(123), // "Tent"
    TENT_124(124), // "Tent"
    TENT_125(125), // "Tent"
    BIG_TENT_126(126), // "Big Tent"
    BIG_TENT_127(127), // "Big Tent"
    BIG_TENT_128(128), // "Big Tent"
    TORTURING_CHAMBER_129(129), // "Torturing Chamber"
    TORTURING_CHAMBER_130(130), // "Torturing Chamber"
    TORTURING_CHAMBER_131(131), // "Torturing Chamber"
    CRYPT_132(132), // "Crypt"
    CRYPT_133(133), // "Crypt"
    CRYPT_134(134), // "Crypt"
    TOWER_135(135), // "Tower"
    TOWER_136(136), // "Tower"
    NEST_137(137), // "Nest"
    TOWER_138(138), // "Tower"
    DRUID_HOUSE_139(139), // "Druid House"
    DRUID_HOUSE_140(140), // "Druid House"
    DRUID_HOUSE_141(141), // "Druid House"
    GATES_142(142), // "Gates"
    GATES_143(143), // "Gates"
    BLACKSMITH_144(144), // "Blacksmith"
    BLACKSMITH_145(145), // "Blacksmith"
    STONEHENGE_146(146), // "Stonehenge"
    STONEHENGE_147(147), // "Stonehenge"
    STONEHENGE_148(148), // "Stonehenge"
    STONEHENGE_149(149), // "Stonehenge"
    STONEHENGE_150(150), // "Stonehenge"
    STONEHENGE_151(151), // "Stonehenge"
    STONEHENGE_152(152), // "Stonehenge"
    STONEHENGE_153(153), // "Stonehenge"
    HOUSE_154(154), // "House"
    HOUSE_155(155), // "House"
    HOUSE_156(156), // "House"
    HOUSE_157(157), // "House"
    HOUSE_158(158), // "House"
    HOUSE_159(159), // "House"
    HOUSE_160(160), // "House"
    HOUSE_161(161), // "House"
    HOUSE_162(162), // "House"
    HOUSE_163(163), // "House"
    HOUSE_164(164), // "House"
    HOUSE_165(165), // "House"
    MINE_166(166), // "Mine"
    MINE_167(167), // "Mine"
    MINE_168(168), // "Mine"
    ORE_169(169), // "Ore"
    ORE_170(170), // "Ore"
    ORE_171(171), // "Ore"
    GRINDER_172(172), // "Grinder"
    GRINDER_173(173), // "Grinder"
    GRINDER_174(174), // "Grinder"
    PYRAMID_175(175), // "Pyramid"
    PYRAMID_176(176), // "Pyramid"
    PYRAMID_177(177), // "Pyramid"
    PYRAMID_178(178); // "Pyramid"

    private static final BuildingText[] VALUES_BY_INDEX = values();

    private final int index;

    /**
     * Generated constructor. not ported.
     */
    BuildingText(int index) {
        this.index = index;
    }

    /**
     * Returns the owning text table id. not ported.
     */
    @Override
    public TextTableId tableId() {
        return TextTableId.BUILDING;
    }

    /**
     * Returns the table-local index. not ported.
     */
    @Override
    public int index() {
        return index;
    }

    /**
     * Returns the matching flat g_StringTable index. not ported.
     */
    public int globalIndex() {
        return tableId().globalIndexOf(index);
    }

    /**
     * Resolves a table-local enum constant by its index. not ported.
     */
    public static BuildingText byIndex(int index) {
        if (index < 0 || index >= VALUES_BY_INDEX.length) {
            throw new IndexOutOfBoundsException("BuildingText index out of range: " + index);
        }
        return VALUES_BY_INDEX[index];
    }
}
