package ua.millfreedom.rom2.text;

// Generated by tools/generate_text_tables.py.
// Source of truth: Main.loadTextFiles() and the configured source files for CutPathsText.
// Do not edit manually.

/**
 * Generated table-local mapping for g_cutpaths loaded from main/text/cutpaths.txt.
 */
public enum CutPathsText implements TextTableLocalEntry {
    INTRO_0(0), // "intro"
    TELEPORT_1(1), // "teleport"
    STARS_2(2), // "stars"
    CROWN_3(3), // "crown"
    KNIGHTS_4(4), // "knights"
    DRUIDS_5(5); // "druids"

    private static final CutPathsText[] VALUES_BY_INDEX = values();

    private final int index;

    /**
     * Generated constructor. not ported.
     */
    CutPathsText(int index) {
        this.index = index;
    }

    /**
     * Returns the owning text table id. not ported.
     */
    @Override
    public TextTableId tableId() {
        return TextTableId.CUTPATHS;
    }

    /**
     * Returns the table-local index. not ported.
     */
    @Override
    public int index() {
        return index;
    }

    /**
     * Returns the matching flat g_StringTable index. not ported.
     */
    public int globalIndex() {
        return tableId().globalIndexOf(index);
    }

    /**
     * Resolves a table-local enum constant by its index. not ported.
     */
    public static CutPathsText byIndex(int index) {
        if (index < 0 || index >= VALUES_BY_INDEX.length) {
            throw new IndexOutOfBoundsException("CutPathsText index out of range: " + index);
        }
        return VALUES_BY_INDEX[index];
    }
}
