package ua.millfreedom.rom2.text;

// Generated by tools/generate_text_tables.py.
// Source of truth: Main.loadTextFiles() and the configured source files for CutSceneText.
// Do not edit manually.

/**
 * Generated table-local mapping for g_cutscene loaded from main/text/cutscene.txt.
 */
public enum CutSceneText implements TextTableLocalEntry {
    INTRO_0(0), // "Intro"
    ASTRAL_TRAVEL_1(1), // "Astral travel"
    STARFALL_2(2), // "Starfall"
    CROWN_3(3), // "Crown"
    KNIGHTS_TRIUMPH_4(4), // "Knights' triumph"
    DRUIDS_TRIUMPH_5(5); // "Druids' triumph"

    private static final CutSceneText[] VALUES_BY_INDEX = values();

    private final int index;

    /**
     * Generated constructor. not ported.
     */
    CutSceneText(int index) {
        this.index = index;
    }

    /**
     * Returns the owning text table id. not ported.
     */
    @Override
    public TextTableId tableId() {
        return TextTableId.CUTSCENE;
    }

    /**
     * Returns the table-local index. not ported.
     */
    @Override
    public int index() {
        return index;
    }

    /**
     * Returns the matching flat g_StringTable index. not ported.
     */
    public int globalIndex() {
        return tableId().globalIndexOf(index);
    }

    /**
     * Resolves a table-local enum constant by its index. not ported.
     */
    public static CutSceneText byIndex(int index) {
        if (index < 0 || index >= VALUES_BY_INDEX.length) {
            throw new IndexOutOfBoundsException("CutSceneText index out of range: " + index);
        }
        return VALUES_BY_INDEX[index];
    }
}
