package ua.millfreedom.rom2.text;

// Generated by tools/generate_text_tables.py.
// Source of truth: Main.loadTextFiles() and the configured source files for DialogsText.
// Do not edit manually.

/**
 * Generated table-local mapping for g_dialogs loaded from main/text/dialogs.txt.
 */
public enum DialogsText implements TextTableLocalEntry {
    OK_0(0), // "Ok"
    CANCEL_1(1), // "Cancel"
    ABORT_2(2), // "Abort"
    RETRY_3(3), // "Retry"
    IGNORE_4(4), // "Ignore"
    EXIT_5(5), // "Exit"
    EXIT_GAME_6(6), // "Exit Game"
    SOUND_OPTIONS_7(7), // "Sound Options"
    RETURN_TO_GAME_8(8), // "Return to Game"
    RANDOM_ORDER_9(9), // "Random Order"
    SELECT_PLAYING_SEQUENCE_10(10), // "Select playing sequence"
    SELECT_TRACK_11(11), // "Select track"
    PLAY_12(12), // "Play"
    PLAY_13(13), // "Play"
    STOP_14(14), // "Stop"
    STOP_15(15), // "Stop"
    MUSIC_VOLUME_16(16), // "Music volume"
    SFX_VOLUME_17(17), // "SFX volume"
    SPEECH_VOLUME_18(18), // "Speech volume"
    MUSIC_VOLUME_19(19), // "Music volume"
    SFX_VOLUME_20(20), // "Sfx volume"
    SPEECH_VOLUME_21(21), // "Speech volume"
    TRACK_22(22), // "Track"
    MUSIC_IS_NOT_AVAILABLE_23(23), // "Music is not available."
    LOAD_GAME_24(24), // "Load Game"
    SELECT_GAME_TO_LOAD_25(25), // "Select Game to load"
    CONFIRM_SELECTION_26(26), // "Confirm selection"
    CANCEL_27(27), // "Cancel"
    EMPTY_SLOT_28(28), // " <<< Empty Slot >>>"
    SAVE_GAME_29(29), // "Save Game"
    ENTER_A_NAME_FOR_THE_SAVED_GAME_30(30), // "Enter a name for the saved game"
    SAVED_GAMES_31(31), // "Saved Games"
    CONFIRM_SELECTION_32(32), // "Confirm selection"
    CANCLE_33(33), // "Cancle"
    SAVE_GAME_34(34), // "~Save Game"
    LOAD_GAME_35(35), // "~Load Game"
    GAME_OPTIONS_36(36), // "Game ~Options"
    SOUND_OPTIONS_37(37), // "Sou~nd Options"
    QUEST_OBJECTIVES_38(38), // "~Quest Objectives"
    END_QUEST_39(39), // "~End Quest"
    RETURN_TO_GAME_40(40), // "~Return to Game"
    RESTART_QUEST_41(41), // "~Restart Quest"
    CHANGE_MAP_42(42), // "Change Map"
    VICTORY_43(43), // "~Victory!"
    EXIT_TO_MAIN_MENU_44(44), // "~Exit to Main Menu"
    EXIT_TO_WINDOWS_45(45), // "Exit to ~Windows"
    DROP_MONEY_46(46), // "Drop money"
    CANCEL_DROP_47(47), // "Cancel drop"
    HOW_MUCH_GOLD_DO_48(48), // "How much gold do"
    YOU_WANT_TO_DROP_49(49), // "you want to drop ?"
    GAME_SPEED_50(50), // "Game Speed"
    GAME_SPEED_51(51), // "Game Speed"
    SMOOTHING_52(52), // "Smoothing"
    SMOOTHING_53(53), // "Smoothing"
    DAY_NIGHT_CHANGES_54(54), // "Day/Night changes"
    DAY_NIGHT_CHANGES_55(55), // "Day/Night changes"
    SHOW_HEALTH_56(56), // "Show Health"
    SHOW_HEALTH_57(57), // "Show Health"
    FORMATION_MODE_58(58), // "Formation Mode"
    FORMATION_MODE_59(59), // "Formation Mode"
    OFF_60(60), // "Off"
    AUTO_61(61), // "Auto"
    ON_62(62), // "On"
    RETREAT_MODE_63(63), // "Retreat Mode"
    RETREAT_MODE_64(64), // "Retreat Mode"
    NEVER_65(65), // "Never"
    LOW_HEALTH_66(66), // "Low Health"
    MEDIUM_HEALTH_67(67), // "Medium Health"
    QUEST_OBJECTIVES_AND_HINTS_68(68), // "Quest Objectives and Hints:"
    ENTER_YOUR_NAME_69(69), // "Enter your name"
    ENTER_YOUR_NAME_70(70), // "Enter your name"
    SELECT_YOUR_SEX_71(71), // "Select your sex"
    MALE_72(72), // "Male"
    FEMALE_73(73), // "Female"
    NOT_AVAILABLE_IN_DEMO_VERSION_74(74), // "Not available in demo version"
    MUSIC_OPTIONS_ARE_NOT_AVAILABLE_NOW_75(75), // "Music options are not available now"
    DIPLOMACY_76(76), // "Diplomacy"
    ABORT_GAME_77(77), // "Abort Game"
    DISPLAY_DAMAGE_POINTS_78(78), // "Display damage points"
    PLAYER_ENEMY_ALLIANCE_VISIBLE_SILENT_79(79), // "    Player           enemy  alliance  visible  silent"
    SELECT_CONNECTION_80(80), // "Select Connection"
    AVAILABLE_PROTOCOLS_81(81), // "Available protocols"
    AVAILABLE_GAMES_82(82), // "Available games"
    GAMES_83(83), // "Games"
    PLAYER_LIST_84(84), // "Player list"
    PLAYERS_85(85), // "Players"
    CREATE_86(86), // "Create"
    JOIN_87(87), // "Join"
    SINGLE_88(88), // "Single"
    REFRESH_89(89), // "Refresh"
    THIS_IS_THE_LIST_OF_RECENTLY_USED_PHONE_NUMBERS_PRESS_DEL_TO_90(90), // "This is the list of recently used phone numbers. Press <Del> to remove an entry."
    ENTER_THE_PHONE_NUMBER_TO_DIAL_91(91), // "Enter the phone number to dial."
    YOUR_PHONE_BOOK_92(92), // "Your phone book."
    SELECT_THE_MODEM_WHICH_YOU_WISH_TO_USE_93(93), // "Select the modem#which you wish to use"
    NO_PARITY_94(94), // "No Parity"
    ODD_PARITY_95(95), // "Odd Parity"
    EVEN_PARITY_96(96), // "Even Parity"
    MARK_PARITY_97(97), // "Mark Parity"
    VALUE_1_BIT_98(98), // "1 bit"
    VALUE_1_5_BITS_99(99), // "1.5 bits"
    VALUE_2_BITS_100(100), // "2 bits"
    RTS_101(101), // "RTS"
    DTR_102(102), // "DTR"
    NONE_103(103), // "None"
    XON_XOFF_104(104), // "Xon/Xoff"
    RTS_DTR_105(105), // "RTS/DTR"
    COM_PORT_106(106), // "COM port:"
    SELECT_BAUD_RATE_107(107), // "Select baud rate:"
    SELECT_PARITY_108(108), // "Select parity:"
    FLOW_CONTROL_109(109), // "Flow control:"
    STOP_BITS_110(110), // "Stop bits:"
    COM_PORT_111(111), // "COM port"
    SELECT_BAUD_RATE_112(112), // "Select baud rate"
    SELECT_PARITY_113(113), // "Select parity"
    FLOW_CONTROL_114(114), // "Flow control"
    STOP_BITS_115(115), // "Stop bits"
    ENTER_THE_COMPUTER_NAME_OR_IP_ADDRESS_OR_LEAVE_IT_BLANK_116(116), // "Enter the computer name or IP address, or leave it blank."
    ENTER_COMPUTER_NAME_OR_IP_ADDRESS_OR_LEAVE_THIS_FIELD_BLANK_TO_117(117), // "Enter computer name#or IP address,#or leave this field#blank to search."
    AVAILABLE_MAPS_118(118), // "Available maps"
    DIALING_NOW_PLEASE_WAIT_119(119), // "Dialing now. Please wait..."
    DIAL_120(120), // "Dial"
    ANSWER_121(121), // "Answer"
    JOIN_122(122), // "Join"
    CREATE_123(123), // "Create"
    GAME_NOT_STARTED_124(124), // "Game not started."
    AT_125(125), // " at"
    CLICK_HERE_TO_DIAL_126(126), // "Click here to dial"
    CLICK_HERE_TO_START_THE_GAME_AND_WAIT_FOR_YOUR_OPPONENT_127(127), // "Click here to start#the game and wait#for your opponent"
    CLICK_HERE_TO_JOIN_128(128), // "Click here to join"
    CLICK_HERE_TO_START_THE_GAME_AND_WAIT_FOR_YOUR_OPPONENT_129(129), // "Click here to start#the game and wait#for your opponent"
    RESET_SETTINGS_130(130), // "Reset settings"
    THIS_WILL_RESET_THE_SETTINGS_TO_THEIR_DEFAULT_VALUES_131(131), // "This will reset#the settings to#their default values"
    MESSAGES_SENT_BY_OTHER_PLAYERS_132(132), // "Messages sent by other players"
    TYPE_YOUR_MESSAGE_TO_OTHER_PLAYERS_HERE_133(133), // "Type your message to other players here"
    MAP_SIZE_134(134), // "Map size"
    RECOMMENDED_NUMBER_OF_PLAYERS_135(135), // "Recommended number of players"
    THE_DIFFICULTY_LEVEL_OF_THE_MAP_MAPS_SHOWN_IN_GRAY_ARE_TOO_136(136), // "The difficulty level of the map.#Maps shown in gray are too strong#or too weak for your chara..."
    PLAYER_LIST_137(137), // "Player list"
    SELECT_MAP_TO_PLAY_138(138), // "Select map to play"
    MAP_NAME_SIZE_LEVEL_139(139), // "  Map name                        Size     Level"
    CHAT_140(140), // "Chat"
    PLAYERS_141(141), // "Players"
    CREATE_OR_JOIN_GAME_142(142), // "Create or Join Game"
    TRACKS_143(143), // "Tracks"
    SAVED_GAMES_144(144), // "Saved Games"
    DIPLOMACY_SETTINGS_145(145), // "Diplomacy Settings"
    SELECT_CONNECTION_FOR_MULTIPLAYER_GAME_146(146), // "Select Connection for Multiplayer Game"
    MODEM_SETTINGS_147(147), // "Modem Settings"
    SERIAL_SETTINGS_148(148), // "Serial Settings"
    TCP_IP_SETTINGS_149(149), // "TCP/IP Settings"
    GAME_OPTIONS_150(150), // "Game Options"
    LOAD_SAVED_GAME_151(151), // "Load Saved Game"
    ENTER_NUMBER_AND_NAME_152(152), // "Enter Number & Name"
    VIEW_CUTSCENES_153(153), // "View Cutscenes"
    CONTINUE_154(154), // "Continue"
    END_QUEST_155(155), // "End Quest"
    TIPS_156(156), // "Tips"
    DELETE_157(157), // "Delete"
    DELETE_SELECTED_SAVED_GAME_158(158), // "Delete selected#saved game"
    AUTOHEALING_159(159), // "AutoHealing"
    NO_160(160), // "No"
    NORMAL_161(161), // "Normal"
    OFTEN_162(162), // "Often"
    CONNECTING_163(163), // "Connecting..."
    AUTOHEALING_MODE_164(164), // "AutoHealing mode"
    ACKNOWLEDGMENTS_165(165), // "Acknowledgments"
    AUTOCAST_FOR_UNITS_166(166), // "AutoCast for units:"
    OWN_167(167), // "Own"
    ALLIES_168(168), // "Allies"
    NEUTRAL_169(169), // "Neutral"
    AUTOCAST_MODE_170(170), // "AutoCast mode:"
    MINIMUM_171(171), // "Minimum"
    AVERAGE_172(172), // "Average"
    MAXIMUM_173(173), // "Maximum"
    AUTOCAST_MODE_174(174), // "AutoCast mode#Minimum: Healing and Shield#Average: additionaly casts Bless and Haste#Maximum:..."
    NAMES_AND_CLANS_175(175); // "Names & Clans"

    private static final DialogsText[] VALUES_BY_INDEX = values();

    private final int index;

    /**
     * Generated constructor. not ported.
     */
    DialogsText(int index) {
        this.index = index;
    }

    /**
     * Returns the owning text table id. not ported.
     */
    @Override
    public TextTableId tableId() {
        return TextTableId.DIALOGS;
    }

    /**
     * Returns the table-local index. not ported.
     */
    @Override
    public int index() {
        return index;
    }

    /**
     * Returns the matching flat g_StringTable index. not ported.
     */
    public int globalIndex() {
        return tableId().globalIndexOf(index);
    }

    /**
     * Resolves a table-local enum constant by its index. not ported.
     */
    public static DialogsText byIndex(int index) {
        if (index < 0 || index >= VALUES_BY_INDEX.length) {
            throw new IndexOutOfBoundsException("DialogsText index out of range: " + index);
        }
        return VALUES_BY_INDEX[index];
    }
}
