package ua.millfreedom.rom2.text;

// Generated by tools/generate_text_tables.py.
// Source of truth: Main.loadTextFiles() and the configured source files for HeroPictureText.
// Do not edit manually.

/**
 * Generated table-local mapping for g_heropicture loaded from main/text/heropicture.txt.
 */
public enum HeroPictureText implements TextTableLocalEntry {
    UNARMED_0(0), // "unarmed"
    SWORDSMAN_1(1), // "swordsman"
    SWORDSMAN_2(2), // "swordsman"
    SWORDSMAN_3(3), // "swordsman"
    SWORDSMAN_4(4), // "swordsman"
    SWORDSMAN2H_5(5), // "swordsman2h"
    CLUBMAN_6(6), // "clubman"
    CLUBMAN_7(7), // "clubman"
    CLUBMAN_8(8), // "clubman"
    CLUBMAN_9(9), // "clubman"
    AXEMAN_10(10), // "axeman"
    AXEMAN2H_11(11), // "axeman2h"
    MAGE_ST_12(12), // "mage_st"
    MAGE_ST_13(13), // "mage_st"
    PIKEMAN_14(14), // "pikeman"
    PIKEMAN_15(15), // "pikeman"
    PIKEMAN_16(16), // "pikeman"
    AXEMAN_17(17), // "axeman"
    AXEMAN2H_18(18), // "axeman2h"
    ARCHER_19(19), // "archer"
    ARCHER_20(20), // "archer"
    XBOWMAN_21(21), // "xbowman"
    BLANK_22(22), // ""
    SONIC_BEAM_23(23), // "Sonic Beam"
    FLAME_THROWER_24(24), // "Flame Thrower"
    SWORDSMAN_25(25); // "swordsman"

    private static final HeroPictureText[] VALUES_BY_INDEX = values();

    private final int index;

    /**
     * Generated constructor. not ported.
     */
    HeroPictureText(int index) {
        this.index = index;
    }

    /**
     * Returns the owning text table id. not ported.
     */
    @Override
    public TextTableId tableId() {
        return TextTableId.HEROPICTURE;
    }

    /**
     * Returns the table-local index. not ported.
     */
    @Override
    public int index() {
        return index;
    }

    /**
     * Returns the matching flat g_StringTable index. not ported.
     */
    public int globalIndex() {
        return tableId().globalIndexOf(index);
    }

    /**
     * Resolves a table-local enum constant by its index. not ported.
     */
    public static HeroPictureText byIndex(int index) {
        if (index < 0 || index >= VALUES_BY_INDEX.length) {
            throw new IndexOutOfBoundsException("HeroPictureText index out of range: " + index);
        }
        return VALUES_BY_INDEX[index];
    }
}
