package ua.millfreedom.rom2.text;

// Generated by tools/generate_text_tables.py.
// Source of truth: Main.loadTextFiles() and the configured source files for SpellsText.
// Do not edit manually.

/**
 * Generated table-local mapping for g_spells loaded from main/text/spells.txt.
 */
public enum SpellsText implements TextTableLocalEntry {
    FIRE_ARROW_HOMING_INFLICTS_FIRE_DAMAGE_TO_A_SINGLE_TARGET_0(0), // "Fire Arrow (Homing)#Inflicts Fire damage to a single target"
    FIREBALL_AREA_INFLICTS_FIRE_DAMAGE_TO_ALL_CAUGHT_IN_ITS_AREA_OF_1(1), // "Fireball (Area)#Inflicts Fire damage to all caught in its area of effect"
    WALL_OF_FIRE_AREA_INFLICTS_FIRE_DAMAGE_CONTINUOUSLY_TO_ALL_2(2), // "Wall of Fire (Area)#Inflicts Fire damage continuously to all caught in the area of effect"
    PROTECTION_FROM_FIRE_HOMING_INCREASES_RESISTANSE_TO_FIRE_MAGIC_3(3), // "Protection from Fire (Homing)#Increases resistanse to Fire magic, lowering damage and duratio..."
    HEAL_HOMING_RESTORES_HEALTH_TO_A_SINGLE_TARGET_4(4), // "Heal (Homing)#Restores health to a single target"
    BLESS_HOMING_INCREASES_WARRIOR_S_CHANCES_TO_DO_MAXIMUM_DAMAGE_5(5), // "Bless (Homing)#Increases warrior's chances to do maximum damage with a hand-held weapon"
    HASTE_HOMING_INCREASES_SPEED_OF_A_SINGLE_UNIT_6(6), // "Haste (Homing)#Increases speed of a single unit"
    DRAIN_LIFE_HOMING_DRAINS_A_SINGLE_VICTIM_S_LIFE_HEALING_THE_7(7), // "Drain Life (Homing)#Drains a single victim's life, healing the caster at the same time"
    PROTECTION_FROM_AIR_HOMING_INCREASES_RESISTANSE_TO_AIR_MAGIC_8(8), // "Protection from Air (Homing)#Increases resistanse to Air magic, lowering damage and duration ..."
    INVISIBILITY_HOMING_RENDERS_A_UNIT_INVISIBLE_THE_UNIT_STILL_CAN_9(9), // "Invisibility (Homing)#Renders a unit invisible. The unit still can be detected, but not visually"
    PRISMATIC_SPRAY_MULTI_TARGET_INFLICTS_AIR_DAMAGE_TO_SEVERAL_10(10), // "Prismatic Spray (Multi-Target)#Inflicts Air damage to several targets at once"
    LIGHTNING_HOMING_INFLICTS_AIR_DAMAGE_TO_A_SINGLE_TARGET_11(11), // "Lightning (Homing)#Inflicts Air damage to a single target"
    ICE_MISSILE_HOMING_INFLICTS_WATER_DAMAGE_TO_A_SINGLE_TARGET_12(12), // "Ice Missile (Homing)#Inflicts Water damage to a single target"
    POISON_CLOUD_AREA_INFLICTS_WATER_DAMAGE_CONTINUOUSLY_TO_ALL_13(13), // "Poison Cloud (Area)#Inflicts Water damage continuously to all caught in the area of effect, a..."
    BLIZZARD_AREA_INFLICTS_WATER_DAMAGE_CONTINUOUSLY_TO_ALL_CAUGHT_14(14), // "Blizzard (Area)#Inflicts Water damage continuously to all caught in the area of effect"
    PROTECTION_FROM_WATER_HOMING_INCREASES_RESISTANSE_TO_WATER_MAGIC_15(15), // "Protection from Water (Homing)#Increases resistanse to Water magic, lowering damage and durat..."
    SUMMON_CASTER_ONLY_SUMMONS_A_MONSTER_TO_DEFEND_THE_CASTER_16(16), // "Summon (Caster Only)#Summons a monster to defend the caster."
    ANIMATED_DEAD_CORPSE_RAISES_ZOMBIE_SKELETON_OR_GHOST_FROM_A_UNIT_17(17), // "Animated Dead (Corpse)#Raises zombie, skeleton, or ghost from a unit's corpse"
    TELEPORT_CASTER_ONLY_TELEPORTS_THE_CASTER_TO_A_SPECIFIED_18(18), // "Teleport (Caster Only)#Teleports the caster to a specified location"
    SHIELD_CASTER_ONLY_CREATES_TEMPORARY_SHIELD_TO_ABSORB_PART_OF_19(19), // "Shield (Caster Only)#Creates temporary shield to absorb part of the incoming damage"
    PROTECTION_FROM_EARTH_HOMING_INCREASES_RESISTANSE_TO_EARTH_MAGIC_20(20), // "Protection from Earth (Homing)#Increases resistanse to Earth magic, lowering damage and durat..."
    STONE_CURSE_HOMING_TEMPORARILY_TURNS_A_SINGLE_TARGET_TO_STONE_21(21), // "Stone Curse (Homing)#Temporarily turns a single target to stone"
    WALL_OF_EARTH_AREA_TEMPORARILY_CREATES_AN_UNPASSABLE_WALL_22(22), // "Wall of Earth (Area)#Temporarily creates an unpassable wall"
    STONE_MISSILE_HOMING_INFLICTS_EARTH_DAMAGE_TO_A_SINGLE_TARGET_23(23); // "Stone Missile (Homing)#Inflicts Earth damage to a single target"

    private static final SpellsText[] VALUES_BY_INDEX = values();

    private final int index;

    /**
     * Generated constructor. not ported.
     */
    SpellsText(int index) {
        this.index = index;
    }

    /**
     * Returns the owning text table id. not ported.
     */
    @Override
    public TextTableId tableId() {
        return TextTableId.SPELLS;
    }

    /**
     * Returns the table-local index. not ported.
     */
    @Override
    public int index() {
        return index;
    }

    /**
     * Returns the matching flat g_StringTable index. not ported.
     */
    public int globalIndex() {
        return tableId().globalIndexOf(index);
    }

    /**
     * Resolves a table-local enum constant by its index. not ported.
     */
    public static SpellsText byIndex(int index) {
        if (index < 0 || index >= VALUES_BY_INDEX.length) {
            throw new IndexOutOfBoundsException("SpellsText index out of range: " + index);
        }
        return VALUES_BY_INDEX[index];
    }
}
