package ua.millfreedom.rom2.text;

// Generated by tools/generate_text_tables.py.
// Source of truth: Main.loadTextFiles() and the configured source files for SpellText.
// Do not edit manually.

/**
 * Generated table-local mapping for g_spell loaded from main/text/spell.txt.
 */
public enum SpellText implements TextTableLocalEntry {
    FIRE_ARROW_0(0), // "Fire Arrow"
    FIREBALL_1(1), // "Fireball"
    WALL_OF_FIRE_2(2), // "Wall of Fire"
    PROTECTION_FROM_FIRE_3(3), // "Protection from Fire"
    ICE_MISSILE_4(4), // "Ice Missile"
    POISON_CLOUD_5(5), // "Poison Cloud"
    BLIZZARD_6(6), // "Blizzard"
    PROTECTION_FROM_WATER_7(7), // "Protection from Water"
    ACID_STREAM_8(8), // "Acid Stream"
    LIGHTNING_9(9), // "Lightning"
    PRISMATIC_SPRAY_10(10), // "Prismatic Spray"
    INVISIBILITY_11(11), // "Invisibility"
    PROTECTION_FROM_AIR_12(12), // "Protection from Air"
    DARKNESS_13(13), // "Darkness"
    LIGHT_14(14), // "Light"
    STONE_MISSILE_15(15), // "Stone Missile"
    WALL_OF_EARTH_16(16), // "Wall of Earth"
    STONE_CURSE_17(17), // "Stone Curse"
    PROTECTION_FROM_EARTH_18(18), // "Protection from Earth"
    BLESS_19(19), // "Bless"
    HASTE_20(20), // "Haste"
    ANIMATE_DEAD_21(21), // "Animate Dead"
    TELEPORT_22(22), // "Teleport"
    HEAL_23(23), // "Heal"
    SUMMON_24(24), // "Summon"
    DRAIN_LIFE_25(25), // "Drain Life"
    SHIELD_26(26), // "Shield"
    CURSE_27(27), // "Curse"
    SLOW_28(28); // "Slow"

    private static final SpellText[] VALUES_BY_INDEX = values();

    private final int index;

    /**
     * Generated constructor. not ported.
     */
    SpellText(int index) {
        this.index = index;
    }

    /**
     * Returns the owning text table id. not ported.
     */
    @Override
    public TextTableId tableId() {
        return TextTableId.SPELL;
    }

    /**
     * Returns the table-local index. not ported.
     */
    @Override
    public int index() {
        return index;
    }

    /**
     * Returns the matching flat g_StringTable index. not ported.
     */
    public int globalIndex() {
        return tableId().globalIndexOf(index);
    }

    /**
     * Converts a 1-based runtime spell id into the matching 0-based g_spell text entry. not ported.
     */
    public static SpellText fromSpellId(int spellId) {
        if (spellId <= 0) {
            throw new IndexOutOfBoundsException("Spell id out of range: " + spellId);
        }
        return byIndex(spellId - 1);
    }

    /**
     * Converts this 0-based g_spell text entry into the matching 1-based runtime spell id. not ported.
     */
    public int toSpellId() {
        return index + 1;
    }

    /**
     * Resolves a table-local enum constant by its index. not ported.
     */
    public static SpellText byIndex(int index) {
        if (index < 0 || index >= VALUES_BY_INDEX.length) {
            throw new IndexOutOfBoundsException("SpellText index out of range: " + index);
        }
        return VALUES_BY_INDEX[index];
    }
}
