package ua.millfreedom.rom2.text;

// Generated by tools/generate_text_tables.py.
// Source of truth: Main.loadTextFiles() and the configured source files for StatsText.
// Do not edit manually.

/**
 * Generated table-local mapping for g_stats loaded from main/text/stats.txt.
 */
public enum StatsText implements TextTableLocalEntry {
    UNUSED_VALUE_0_0(0), // "unused_value_0"
    BLANK_1(1), // ""
    BODY_2(2), // "Body"
    MIND_3(3), // "Mind"
    AGILITY_4(4), // "Agility"
    SPIRIT_5(5), // "Spirit"
    HEALTH_6(6), // "Health"
    MAX_HEALTH_7(7), // "Max Health"
    HEALTH_REGENERATION_8(8), // "Health Regeneration"
    MANA_9(9), // "Mana"
    MAX_MANA_10(10), // "Max Mana"
    MANA_REGENERATION_11(11), // "Mana Regeneration"
    ATTACK_12(12), // "Attack"
    DAMAGE_13(13), // "Damage"
    DAMAGE_14(14), // "Damage"
    DEFENSE_15(15), // "Defense"
    ABSORPTION_16(16), // "Absorption"
    SPEED_17(17), // "Speed"
    TURNING_SPEED_18(18), // "Turning Speed"
    SIGHT_19(19), // "Sight"
    UNUSED_20(20), // "(unused)"
    PROTECTION_FROM_FIRE_21(21), // "Protection from Fire"
    PROTECTION_FROM_WATER_22(22), // "Protection from Water"
    PROTECTION_FROM_AIR_23(23), // "Protection from Air"
    PROTECTION_FROM_EARTH_24(24), // "Protection from Earth"
    PROTECTION_FROM_ASTRAL_25(25), // "Protection from Astral"
    UNUSED_26(26), // "(unused)"
    BLADE_SKILL_27(27), // "Blade Skill"
    AXE_SKILL_28(28), // "Axe Skill"
    BLUDGEON_SKILL_29(29), // "Bludgeon Skill"
    PIKE_SKILL_30(30), // "Pike Skill"
    SHOOTING_SKILL_31(31), // "Shooting Skill"
    UNUSED_32(32), // "(unused)"
    FIRE_SKILL_33(33), // "Fire Skill"
    WATER_SKILL_34(34), // "Water Skill"
    AIR_SKILL_35(35), // "Air Skill"
    EARTH_SKILL_36(36), // "Earth Skill"
    ASTRAL_SKILL_37(37), // "Astral Skill"
    RANGE_38(38), // "Range"
    MAGIC_LORE_39(39), // "Magic Lore"
    CREATURE_LORE_40(40), // "Creature Lore"
    OF_41(41), // "of ..."
    CASTS_42(42), // "casts ..."
    DAMAGE_43(43), // "Damage"
    FIRE_DAMAGE_44(44), // "Fire Damage"
    WATER_DAMAGE_45(45), // "Water Damage"
    AIR_DAMAGE_46(46), // "Air Damage"
    EARTH_DAMAGE_47(47), // "Earth Damage"
    ASTRAL_DAMAGE_48(48), // "Astral Damage"
    DAMAGE_49(49); // "Damage"

    private static final StatsText[] VALUES_BY_INDEX = values();

    private final int index;

    /**
     * Generated constructor. not ported.
     */
    StatsText(int index) {
        this.index = index;
    }

    /**
     * Returns the owning text table id. not ported.
     */
    @Override
    public TextTableId tableId() {
        return TextTableId.STATS;
    }

    /**
     * Returns the table-local index. not ported.
     */
    @Override
    public int index() {
        return index;
    }

    /**
     * Returns the matching flat g_StringTable index. not ported.
     */
    public int globalIndex() {
        return tableId().globalIndexOf(index);
    }

    /**
     * Resolves a table-local enum constant by its index. not ported.
     */
    public static StatsText byIndex(int index) {
        if (index < 0 || index >= VALUES_BY_INDEX.length) {
            throw new IndexOutOfBoundsException("StatsText index out of range: " + index);
        }
        return VALUES_BY_INDEX[index];
    }
}
