package ua.millfreedom.rom2.text;

// Generated by tools/generate_text_tables.py.
// Source of truth: Main.loadTextFiles() and the configured source files for TextTableId.
// Do not edit manually.

import java.util.HashMap;
import java.util.Map;

/**
 * Generated text-table identifiers for Main.loadTextFiles() and other CTextFile::LoadAndParse callers.
 */
public enum TextTableId {
    MAIN("g_main", "main/text/main.txt", 0, 369),
    HEROPICTURE("g_heropicture", "main/text/heropicture.txt", 369, 26),
    STATS("g_stats", "main/text/stats.txt", 395, 50),
    SPELLS("g_spells", "main/text/spells.txt", 445, 24),
    SPELL("g_spell", "main/text/spell.txt", 469, 29),
    DIALOGS("g_dialogs", "main/text/dialogs.txt", 498, 176),
    UNITNAME("g_unitname", "main/text/unitname.txt", 674, 108),
    BUILDING("g_building", "main/text/building.txt", 782, 179),
    ITEMNAME("g_itemname", "main/text/itemname.txt", 961, 500),
    NPCNAMES("g_npcnames", "main/text/npcnames.txt", 1461, 2370),
    CUTSCENE("g_cutscene", "main/text/cutscene.txt", 3831, 6),
    CUTPATHS("g_cutpaths", "main/text/cutpaths.txt", 3837, 6),
    TUNES("g_tunes", "main/text/tunes.txt", 3843, 21),
    PATCH("g_patch", "patch/patch.txt", 3864, 235),
    CREDITS("credits", "main/text/credits.txt", -1, 0);

    private static final Map<String, TextTableId> BY_ARRAY_NAME = createByArrayName();

    private final String arrayName;
    private final String resourcePath;
    private final int globalStartIndex;
    private final int entryCount;

    /**
     * Generated constructor. not ported.
     */
    TextTableId(String arrayName, String resourcePath, int globalStartIndex, int entryCount) {
        this.arrayName = arrayName;
        this.resourcePath = resourcePath;
        this.globalStartIndex = globalStartIndex;
        this.entryCount = entryCount;
    }

    /**
     * Returns the canonical CTextFile table name. For Main.loadTextFiles() entries, this matches the native g_* symbol. not ported.
     */
    public String arrayName() {
        return arrayName;
    }

    /**
     * Returns whether this table participates in the flat g_StringTable index space. not ported.
     */
    public boolean isStringTableBacked() {
        return globalStartIndex >= 0;
    }

    /**
     * Returns the resource path used when the table is loaded. not ported.
     */
    public String resourcePath() {
        return resourcePath;
    }

    /**
     * Returns the first flat g_StringTable index owned by this table. not ported.
     */
    public int globalStartIndex() {
        return globalStartIndex;
    }

    /**
     * Returns the number of entries in this table. not ported.
     */
    public int entryCount() {
        return entryCount;
    }

    /**
     * Returns the first flat g_StringTable index after this table. not ported.
     */
    public int globalEndExclusive() {
        return globalStartIndex + entryCount;
    }

    /**
     * Checks whether the provided flat g_StringTable index belongs to this table. not ported.
     */
    public boolean containsGlobalIndex(int globalIndex) {
        return isStringTableBacked() && globalIndex >= globalStartIndex && globalIndex < globalEndExclusive();
    }

    /**
     * Converts a local table index into a flat g_StringTable index. not ported.
     */
    public int globalIndexOf(int indexInTable) {
        if (indexInTable < 0 || indexInTable >= entryCount) {
            throw new IndexOutOfBoundsException(name() + " index out of range: " + indexInTable);
        }
        return globalStartIndex + indexInTable;
    }

    /**
     * Resolves a table id from its canonical CTextFile table name. not ported.
     */
    public static TextTableId fromArrayName(String arrayName) {
        TextTableId tableId = BY_ARRAY_NAME.get(arrayName);
        if (tableId == null) {
            throw new IllegalArgumentException("Unknown text array: " + arrayName);
        }
        return tableId;
    }

    /**
     * Resolves a table id from a flat g_StringTable index. not ported.
     */
    public static TextTableId fromGlobalIndex(int globalIndex) {
        for (TextTableId tableId : values()) {
            if (tableId.containsGlobalIndex(globalIndex)) {
                return tableId;
            }
        }
        throw new IndexOutOfBoundsException("g_StringTable index out of range: " + globalIndex);
    }

    /**
     * Builds the array-name lookup map. not ported.
     */
    private static Map<String, TextTableId> createByArrayName() {
        Map<String, TextTableId> byArrayName = new HashMap<>();
        for (TextTableId tableId : values()) {
            byArrayName.put(tableId.arrayName, tableId);
        }
        return byArrayName;
    }
}
