package ua.millfreedom.rom2.text;

// Generated by tools/generate_text_tables.py.
// Source of truth: Main.loadTextFiles() and the configured source files for TunesText.
// Do not edit manually.

/**
 * Generated table-local mapping for g_tunes loaded from main/text/tunes.txt.
 */
public enum TunesText implements TextTableLocalEntry {
    B00_WAV_IN_RESTLESS_WAITING_0(0), // "b00.wav=In Restless Waiting"
    B01_WAV_ASTRAL_THREAT_1(1), // "b01.wav=Astral Threat"
    B02_WAV_WAR_OF_DRUIDS_2(2), // "b02.wav=War of Druids"
    B03_WAV_TRAGEDY_OF_BATTLE_3(3), // "b03.wav=Tragedy of Battle"
    B04_WAV_ANCIENT_WOODS_4(4), // "b04.wav=Ancient Woods"
    B05_WAV_THE_AXE_SONG_5(5), // "b05.wav=The Axe Song"
    B06_WAV_DESERT_6(6), // "b06.wav=Desert"
    B07_WAV_THE_SWORD_SONG_7(7), // "b07.wav=The Sword Song"
    B08_WAV_MYSTERIOUS_LAND_8(8), // "b08.wav=Mysterious Land"
    B09_WAV_A_LONG_WAY_9(9), // "b09.wav=A Long Way"
    B10_WAV_WAR_OF_ORCS_10(10), // "b10.wav=War of Orcs"
    B11_WAV_COLD_FURY_11(11), // "b11.wav=Cold fury"
    B12_WAV_WAR_OF_ZOMBIES_12(12), // "b12.wav=War of Zombies"
    B13_WAV_GRAVEYARD_13(13), // "b13.wav=Graveyard"
    B14_WAV_PLAGAT_14(14), // "b14.wav=Plagat"
    B15_WAV_DRUIDS_DWELLING_15(15), // "b15.wav=Druids dwelling"
    B16_WAV_KAARG_16(16), // "b16.wav=Kaarg"
    CHRGEN_WAV_CHARACTER_GENERATOR_17(17), // "chrgen.wav=Character generator"
    CREDITS_WAV_CREDITS_18(18), // "credits.wav=Credits"
    MAP_WAV_GLOBAL_MAP_19(19), // "map.wav=Global map"
    MENU_WAV_MAIN_MENU_20(20); // "menu.wav=Main Menu"

    private static final TunesText[] VALUES_BY_INDEX = values();

    private final int index;

    /**
     * Generated constructor. not ported.
     */
    TunesText(int index) {
        this.index = index;
    }

    /**
     * Returns the owning text table id. not ported.
     */
    @Override
    public TextTableId tableId() {
        return TextTableId.TUNES;
    }

    /**
     * Returns the table-local index. not ported.
     */
    @Override
    public int index() {
        return index;
    }

    /**
     * Returns the matching flat g_StringTable index. not ported.
     */
    public int globalIndex() {
        return tableId().globalIndexOf(index);
    }

    /**
     * Resolves a table-local enum constant by its index. not ported.
     */
    public static TunesText byIndex(int index) {
        if (index < 0 || index >= VALUES_BY_INDEX.length) {
            throw new IndexOutOfBoundsException("TunesText index out of range: " + index);
        }
        return VALUES_BY_INDEX[index];
    }
}
