package ua.millfreedom.rom2.text;

// Generated by tools/generate_text_tables.py.
// Source of truth: Main.loadTextFiles() and the configured source files for UnitNameText.
// Do not edit manually.

/**
 * Generated table-local mapping for g_unitname loaded from main/text/unitname.txt.
 */
public enum UnitNameText implements TextTableLocalEntry {
    BLANK_0(0), // ""
    PEASANT_1(1), // "Peasant"
    BLANK_2(2), // ""
    SWORDSMAN_3(3), // "Swordsman"
    SWORDSMAN_4(4), // "Swordsman"
    SWORDSMAN_5(5), // "Swordsman"
    BLANK_6(6), // ""
    AXEMAN_7(7), // "Axeman"
    AXEMAN_8(8), // "Axeman"
    AXEMAN_9(9), // "Axeman"
    CLUBMAN_10(10), // "Clubman"
    CLUBMAN_11(11), // "Clubman"
    PIKEMAN_12(12), // "Pikeman"
    PIKEMAN_13(13), // "Pikeman"
    ARCHER_14(14), // "Archer"
    CROSSBOWMAN_15(15), // "Crossbowman"
    BLANK_16(16), // ""
    HORSEMAN_17(17), // "Horseman"
    HORSEMAN_18(18), // "Horseman"
    HORSEMAN_19(19), // "Horseman"
    LANCER_20(20), // "Lancer"
    LANCER_21(21), // "Lancer"
    BLANK_22(22), // ""
    MAGE_23(23), // "Mage"
    MAGE_24(24), // "Mage"
    BLANK_25(25), // ""
    CATAPULT_26(26), // "Catapult"
    CATAPULT_27(27), // "Catapult"
    BLANK_28(28), // ""
    BLANK_29(29), // ""
    BLANK_30(30), // ""
    BLANK_31(31), // ""
    BLANK_32(32), // ""
    BLANK_33(33), // ""
    BLANK_34(34), // ""
    BLANK_35(35), // ""
    BLANK_36(36), // ""
    BLANK_37(37), // ""
    BLANK_38(38), // ""
    BLANK_39(39), // ""
    BLANK_40(40), // ""
    BLANK_41(41), // ""
    BLANK_42(42), // ""
    BLANK_43(43), // ""
    BLANK_44(44), // ""
    BLANK_45(45), // ""
    BLANK_46(46), // ""
    BLANK_47(47), // ""
    BLANK_48(48), // ""
    BLANK_49(49), // ""
    BLANK_50(50), // ""
    BLANK_51(51), // ""
    BLANK_52(52), // ""
    BLANK_53(53), // ""
    BLANK_54(54), // ""
    BLANK_55(55), // ""
    BLANK_56(56), // ""
    BLANK_57(57), // ""
    BLANK_58(58), // ""
    BLANK_59(59), // ""
    BLANK_60(60), // ""
    BLANK_61(61), // ""
    BLANK_62(62), // ""
    BLANK_63(63), // ""
    GOBLIN_64(64), // "Goblin"
    ORC_ARCHER_65(65), // "Orc Archer"
    OGRE_66(66), // "Ogre"
    WEREWOLF_67(67), // "Werewolf"
    TROLL_68(68), // "Troll"
    SPIRIT_69(69), // "Spirit"
    BAT_70(70), // "Bat"
    DRAGON_71(71), // "Dragon"
    URD_72(72), // "Urd"
    GIANT_BEE_73(73), // "Giant Bee"
    SQUIRREL_74(74), // "Squirrel"
    BONE_SNAKE_75(75), // "Bone Snake"
    TURTLE_76(76), // "Turtle"
    FROG_77(77), // "Frog"
    PLANT_78(78), // "Plant"
    GOBLIN_79(79), // "Goblin"
    ORC_WARRIOR_80(80), // "Orc Warrior"
    ORC_SHAMAN_81(81), // "Orc Shaman"
    ZOMBIE_82(82), // "Zombie"
    ZOMBIE_83(83), // "Zombie"
    ZOMBIE_84(84), // "Zombie"
    ZOMBIE_85(85), // "Zombie"
    ZOMBIE_86(86), // "Zombie"
    ZOMBIE_87(87), // "Zombie"
    ZOMBIE_88(88), // "Zombie"
    SKELETON_89(89), // "Skeleton"
    SKELETON_90(90), // "Skeleton"
    SKELETON_91(91), // "Skeleton"
    SKELETON_92(92), // "Skeleton"
    SKELETON_93(93), // "Skeleton"
    SKELETON_94(94), // "Skeleton"
    SKELETON_95(95), // "Skeleton"
    SKELETON_96(96), // "Skeleton"
    LICH_97(97), // "Lich"
    LICH_98(98), // "Lich"
    NECROMANCER_99(99), // "Necromancer"
    DRUID_100(100), // "Druid"
    ORC_101(101), // "Orc"
    TROLL_102(102), // "Troll"
    WOLF_103(103), // "Wolf"
    SPIDER_104(104), // "Spider"
    SUCCUBUS_105(105), // "Succubus"
    LIZARD_106(106), // "Lizard"
    SHEEP_107(107); // "Sheep"

    private static final UnitNameText[] VALUES_BY_INDEX = values();

    private final int index;

    /**
     * Generated constructor. not ported.
     */
    UnitNameText(int index) {
        this.index = index;
    }

    /**
     * Returns the owning text table id. not ported.
     */
    @Override
    public TextTableId tableId() {
        return TextTableId.UNITNAME;
    }

    /**
     * Returns the table-local index. not ported.
     */
    @Override
    public int index() {
        return index;
    }

    /**
     * Returns the matching flat g_StringTable index. not ported.
     */
    public int globalIndex() {
        return tableId().globalIndexOf(index);
    }

    /**
     * Resolves a table-local enum constant by its index. not ported.
     */
    public static UnitNameText byIndex(int index) {
        if (index < 0 || index >= VALUES_BY_INDEX.length) {
            throw new IndexOutOfBoundsException("UnitNameText index out of range: " + index);
        }
        return VALUES_BY_INDEX[index];
    }
}
