package ua.millfreedom.rom2.model.enums;

public enum BuildingId {
    EMPTY(0, ""),
    GOBLIN_HUT(1, "Goblin Hut"),
    GOBLIN_HUT_2(2, "Goblin Hut 2"),
    ORC_HUT(3, "Orc Hut"),
    ORC_HUT_2(4, "Orc Hut 2"),
    MILL(5, "Mill"),
    MILL_2(6, "Mill 2"),
    MILL_3(7, "Mill 3"),
    WELL(8, "Well"),
    PIZANT_HUT(9, "Pizant Hut"),
    PIZANT_HUT_2(10, "Pizant Hut 2"),
    CHURCH(11, "Church"),
    TOWER(12, "Tower"),
    TOWER_2(13, "Tower 2"),
    CAVE(14, "Cave"),
    MAGIC_WELL_2(15, "Magic Well 2"),
    MAGIC_WELL_3(16, "Magic Well 3"),
    HUMAN_HOUSE_3A(17, "Human House 3a"),
    HUMAN_HOUSE_3B(18, "Human House 3b"),
    HUMAN_HOUSE_2A(19, "Human House 2a"),
    HUMAN_HOUSE_2B(20, "Human House 2b"),
    OGRE_HOUSE(21, "Ogre House"),
    OGRE_HOUSE_2(22, "Ogre House 2"),
    OGRE_HOUSE_3(23, "Ogre House 3"),
    BEE_HOUSE(24, "Bee House"),
    BEE_HOUSE_2(25, "Bee House 2"),
    LEGS_HOUSE(26, "Leg's House"),
    MAGIC_SYMBOL(27, "Magic Symbol"),
    SWITCH(28, "Switch"),
    SWITCH_2(29, "Switch 2"),
    RUINS(30, "Ruins"),
    RUINS_2(31, "Ruins 2"),
    RUINS_3(32, "Ruins 3"),
    VERTICAL_WOODEN_BRIDGE(33, "Vertical Wooden Bridge"),
    SHOP(34, "Shop"),
    SHOP_2(35, "Shop 2"),
    HANGING_PEASANT(36, "Hanging Peasant"),
    HORISONTAL_WOODEN_BRIDGE(37, "Horisontal Wooden Bridge"),
    HORISONTAL_BRIDGE(38, "Horisontal Bridge"),
    KINGS_GRAVE_1(39, "King's Grave 1"),
    KINGS_GRAVE_2(40, "King's Grave 2"),
    COMMON_GRAVE_1(41, "Common Grave 1"),
    COMMON_GRAVE_2(42, "Common Grave 2"),
    INN_1(43, "Inn 1"),
    INN_2(44, "Inn 2"),
    INN_3(45, "Inn 3"),
    GUARD_TOWER_1(46, "Guard Tower 1"),
    GUARD_TOWER_2(47, "Guard Tower 2"),
    TELEPORT_PAD(48, "Teleport Pad"),
    TRAINING_SCHOOL_1(49, "Training School 1"),
    TRAINING_SCHOOL_2(50, "Training School 2"),
    TRAINING_SCHOOL_3(51, "Training School 3"),
    VERTICAL_BRIDGE(52, "Vertical Bridge"),
    CAMP_FIRE(53, "Camp Fire"),
    SKRAKAN_TOWER(54, "Skrakan Tower"),
    SKRAKAN_TOWER_2(55, "Skrakan Tower 2"),
    MAGES_TOWER(56, "Mage's tower"),
    CASTLE(57, "Castle"),
    SPHINX(58, "Sphinx"),
    SPHINX_2(59, "Sphinx 2"),
    SPHINX_3(60, "Sphinx 3"),
    SPHINX_4(61, "Sphinx 4"),
    SPHINX_5(62, "Sphinx 5"),
    SPHINX_6(63, "Sphinx 6"),
    SPHINX_7(64, "Sphinx 7"),
    SPHINX_8(65, "Sphinx 8"),
    MULTIPLAYER_CHURCH(66, "Multiplayer Church"),
    MULTIPLAYER_INN_1(67, "Multiplayer Inn 1"),
    MULTIPLAYER_INN_2(68, "Multiplayer Inn 2"),
    MULTIPLAYER_INN_3(69, "Multiplayer Inn 3"),
    POINTER_1(70, "Pointer 1"),
    POINTER_2(71, "Pointer 2"),
    POINTER_3(72, "Pointer 3"),
    POINTER_4(73, "Pointer 4"),
    POINTER_5(74, "Pointer 5"),
    POINTER_6(75, "Pointer 6"),
    ALTAR_1(76, "Altar 1"),
    ALTAR_2(77, "Altar 2"),
    NECRO_HOUSE_1(78, "Necro House 1"),
    NECRO_HOUSE_2(79, "Necro House 2"),
    NECRO_HOUSE_3(80, "Necro House 3"),
    SHED_1(81, "Shed 1"),
    SHED_2(82, "Shed 2"),
    SHED_3(83, "Shed 3"),
    ORC_SHAMAN_HOUSE_1(84, "Orc Shaman House 1"),
    ORC_SHAMAN_HOUSE_2(85, "Orc Shaman House 2"),
    ORC_SHAMAN_HOUSE_3(86, "Orc Shaman House 3"),
    BIG_HUMAN_HOUSE_1(87, "Big Human House 1"),
    BIG_HUMAN_HOUSE_2(88, "Big Human House 2"),
    BIG_HUMAN_HOUSE_3(89, "Big Human House 3"),
    KAARG_SHOP_1(90, "Kaarg Shop 1"),
    KAARG_SHOP_2(91, "Kaarg Shop 2"),
    KAARG_SHOP_3(92, "Kaarg Shop 3"),
    MULTIPLAYER_KAARG_SHOP_1(93, "Multiplayer Kaarg Shop 1"),
    MULTIPLAYER_KAARG_SHOP_2(94, "Multiplayer Kaarg Shop 2"),
    MULTIPLAYER_KAARG_SHOP_3(95, "Multiplayer Kaarg Shop 3"),
    KAARG_INN_1(96, "Kaarg Inn 1"),
    KAARG_INN_2(97, "Kaarg Inn 2"),
    KAARG_INN_3(98, "Kaarg Inn 3"),
    MULTIPLAYER_KAARG_INN_1(99, "Multiplayer Kaarg Inn 1"),
    MULTIPLAYER_KAARG_INN_2(100, "Multiplayer Kaarg Inn 2"),
    MULTIPLAYER_KAARG_INN_3(101, "Multiplayer Kaarg Inn 3"),
    DRUID_SHOP_1(102, "Druid Shop 1"),
    DRUID_SHOP_2(103, "Druid Shop 2"),
    DRUID_SHOP_3(104, "Druid Shop 3"),
    MULTIPLAYER_DRUID_SHOP_1(105, "Multiplayer Druid Shop 1"),
    MULTIPLAYER_DRUID_SHOP_2(106, "Multiplayer Druid Shop 2"),
    MULTIPLAYER_DRUID_SHOP_3(107, "Multiplayer Druid Shop 3"),
    DRUID_INN_1(108, "Druid Inn 1"),
    DRUID_INN_2(109, "Druid Inn 2"),
    DRUID_INN_3(110, "Druid Inn 3"),
    MULTIPLAYER_DRUID_INN_1(111, "Multiplayer Druid Inn 1"),
    MULTIPLAYER_DRUID_INN_2(112, "Multiplayer Druid Inn 2"),
    MULTIPLAYER_DRUID_INN_3(113, "Multiplayer Druid Inn 3"),
    BARBARIAN_HUT_1(114, "Barbarian Hut 1"),
    BARBARIAN_HUT_2(115, "Barbarian Hut 2"),
    BARBARIAN_HUT_3(116, "Barbarian Hut 3"),
    CRATER(117, "Crater"),
    VIGVAM_1(118, "Vigvam 1"),
    VIGVAM_2(119, "Vigvam 2"),
    VIGVAM_3(120, "Vigvam 3"),
    OPEN_GRAVE_1(121, "Open Grave 1"),
    OPEN_GRAVE_2(122, "Open Grave 2"),
    OPEN_GRAVE_3(123, "Open Grave 3"),
    TENT_1(124, "Tent 1"),
    TENT_2(125, "Tent 2"),
    TENT_3(126, "Tent 3"),
    BIG_TENT_1(127, "Big tent 1"),
    BIG_TENT_2(128, "Big tent 2"),
    BIG_TENT_3(129, "Big tent 3"),
    TORTURE_1(130, "Torture 1"),
    TORTURE_2(131, "Torture 2"),
    TORTURE_3(132, "Torture 3"),
    SCLEP_1(133, "Sclep 1"),
    SCLEP_2(134, "Sclep 2"),
    SCLEP_3(135, "Sclep 3"),
    KAARG_TOWER_1(136, "Kaarg Tower 1"),
    KAARG_TOWER_2(137, "Kaarg Tower 2"),
    DRAGONS_NEST(138, "Dragon's nest"),
    NECRO_TOWER(139, "Necro Tower"),
    DRUID_HOUSE_1(140, "Druid House 1"),
    DRUID_HOUSE_2(141, "Druid House 2"),
    DRUID_HOUSE_3(142, "Druid House 3"),
    GRAVE_DOORS_1(143, "Grave Doors 1"),
    GRAVE_DOORS_2(144, "Grave Doors 2"),
    BLACKSMITH_1(145, "BlackSmith 1"),
    BLACKSMITH_2(146, "BlackSmith 2"),
    STONEHENGE_1(147, "StoneHenge 1"),
    STONEHENGE_2(148, "StoneHenge 2"),
    STONEHENGE_3(149, "StoneHenge 3"),
    STONEHENGE_4(150, "StoneHenge 4"),
    STONEHENGE_5(151, "StoneHenge 5"),
    STONEHENGE_6(152, "StoneHenge 6"),
    STONEHENGE_7(153, "StoneHenge 7"),
    STONEHENGE_8(154, "StoneHenge 8"),
    BARBARIAN_HUT_4(155, "Barbarian Hut 4"),
    BARBARIAN_HUT_5(156, "Barbarian Hut 5"),
    BARBARIAN_HUT_6(157, "Barbarian Hut 6"),
    BARBARIAN_HUT_7(158, "Barbarian Hut 7"),
    BARBARIAN_HUT_8(159, "Barbarian Hut 8"),
    BARBARIAN_HUT_9(160, "Barbarian Hut 9"),
    KAARG_HUT_1(161, "Kaarg Hut 1"),
    KAARG_HUT_2(162, "Kaarg Hut 2"),
    KAARG_HUT_3(163, "Kaarg Hut 3"),
    KAARG_HUT_4(164, "Kaarg Hut 4"),
    KAARG_HUT_5(165, "Kaarg Hut 5"),
    KAARG_HUT_6(166, "Kaarg Hut 6"),
    MINE_1(167, "Mine 1"),
    MINE_2(168, "Mine 2"),
    MINE_3(169, "Mine 3"),
    ORE_1(170, "Ore 1"),
    ORE_2(171, "Ore 2"),
    ORE_3(172, "Ore 3"),
    STONECRUSHER_1(173, "StoneCrusher 1"),
    STONECRUSHER_2(174, "StoneCrusher 2"),
    STONECRUSHER_3(175, "StoneCrusher 3"),
    PYRAMID_1(176, "Pyramid 1"),
    PYRAMID_2(177, "Pyramid 2"),
    PYRAMID_3(178, "Pyramid 3"),
    PYRAMID_4(179, "Pyramid 4"),
    UNKNOWN(-1, "unknown");

    private static final BuildingId[] BY_ID = createLookup();

    public final int id;
    public final String tableName;

    BuildingId(int id, String tableName) {
        this.id = id;
        this.tableName = tableName;
    }

    public static BuildingId fromId(int id) {
        if (id < 0 || id >= BY_ID.length) {
            return UNKNOWN;
        }
        BuildingId buildingId = BY_ID[id];
        return buildingId == null ? UNKNOWN : buildingId;
    }

    public boolean isBetween(BuildingId from, BuildingId to) {
        return id >= from.id && id <= to.id;
    }

    private static BuildingId[] createLookup() {
        int maxId = PYRAMID_4.id;
        BuildingId[] values = new BuildingId[maxId + 1];
        for (BuildingId buildingId : BuildingId.values()) {
            if (buildingId.id >= 0) {
                values[buildingId.id] = buildingId;
            }
        }
        return values;
    }
}
