package ua.millfreedom.rom2.model.enums;

import java.util.HashMap;
import java.util.Map;

/**
 * Packet IDs recovered from CGameAction descendants, the server decode map in CServerApp::decodeIncomingGameAction,
 * and the packet-stat label map in CServerApp::writePacketStatsLog @005060DA.
 */
public enum GameActionId {
    UNKNOWN_ACTION_00(0x00),
    PLAYER_JOIN_ACTION_02(0x02),
    NO_PAYLOAD_ACTION_03(0x03),
    REQUEST_MAP_LOAD_ACTION_04(0x04),
    MAP_LOAD_COMPLETE_ACTION_05(0x05),
    LOAD_SCENARIO_ACTION_06(0x06),
    SAVE_GAME_REQUEST_ACTION_07(0x07),
    LOAD_GAME_REQUEST_ACTION_08(0x08),
    CLIENT_SHUTDOWN_REQUEST_ACTION_09(0x09),
    NO_PAYLOAD_ACTION_0A(0x0A),
    TWO_DWORD_ACTION_0B(0x0B),
    FIXED_DWORD_ACTION_0E(0x0E),
    LOGIN_REQUEST_ACTION_0F(0x0F),
    STAND_STILL_ORDER_ACTION_12(0x12),
    PICKUP_ALL_SACKS_ACTION_13(0x13),
    RETREAT_ORDER_ACTION_14(0x14),
    MOVE_ORDER_ACTION_16(0x16),
    GUARD_ORDER_ACTION_17(0x17),
    STAND_GROUND_ORDER_ACTION_18(0x18),
    ATTACK_TARGET_ORDER_ACTION_19(0x19),
    ATTACK_CELL_ORDER_ACTION_1A(0x1A),
    DEFEND_TARGET_ORDER_ACTION_1B(0x1B),
    UNIT_TOKEN_LIST_ACTION_1C(0x1C),
    PATROL_ORDER_ACTION_1D(0x1D),
    CAST_SPELL_AT_UNIT_ACTION_1E(0x1E),
    CAST_SPELL_AT_POINT_ACTION_1F(0x1F),
    PICKUP_ORDER_ACTION_21(0x21),
    INVENTORY_TRANSFER_ACTION_22(0x22),
    DROP_GOLD_ACTION_23(0x23),
    ENTER_TOWN_ORDER_ACTION_24(0x24),
    CANCEL_UNIT_SPELL_EFFECT_ACTION_25(0x25),
    CANCEL_POINT_SPELL_EFFECT_ACTION_26(0x26),
    OPEN_SHOP_DIALOG_ACTION_32(0x32),
    SHOP_BUY_ACTION_33(0x33),
    SHOP_SELL_ACTION_34(0x34),
    UNDO_SHOP_ACTION_35(0x35),
    CLOSE_SHOP_DIALOG_ACTION_36(0x36),
    ENTER_INN_ACTION_38(0x38),
    MAP_CHUNK_TRANSFER_COMPLETE_ACTION_39(0x39),
    LEAVE_INN_ACTION_3A(0x3A),
    REQUEST_MAP_CHUNK_ACTION_3B(0x3B),
    TWO_DWORD_ACTION_3D(0x3D),
    ADJUST_PLAYER_GOLD_ACTION_3E(0x3E),
    REFRESH_SHOP_SHELVES_ACTION_3F(0x3F),
    TWO_DWORD_ACTION_40(0x40),
    UPDATE_DIPLOMACY_RELATIONS_ACTION_45(0x45),
    UPDATE_BATTLE_PREFERENCE_ACTION_46(0x46),
    SUBMIT_CHARACTER_SETUP_ACTION_48(0x48),
    NAMED_CHARACTER_SPAWN_REQUEST_ACTION_49(0x49),
    REQUEST_PLAYER_STATE_RESYNC_ACTION_4A(0x4A),
    RETURN_AFTER_DEATH_ACTION_4B(0x4B),
    REVIVE_STUCK_HERO_ACTION_4C(0x4C),
    NEW_SEGMENT_ACTION_64(0x64),
    TWO_DWORD_ACTION_65(0x65),
    MONEY_ACTION_67(0x67),
    UNIT_SHOWN_ACTION_69(0x69),
    SACK_REMOVED_ACTION_6A(0x6A),
    UNIT_MOVE_ACTION_6B(0x6B),
    UNIT_CHANGE_ACTION_6C(0x6C),
    UNIT_TURN_ACTION_6D(0x6D),
    UNIT_CHANGE_ACTION_6E(0x6E),
    UNIT_CHANGE_ACTION_6F(0x6F),
    UNIT_CHANGE_ACTION_70(0x70),
    UNIT_ATTACK_ACTION_71(0x71),
    RANGED_ATTACK_ACTION_72(0x72),
    UNIT_DAMAGED_ACTION_73(0x73),
    UNIT_HIDDEN_ACTION_74(0x74),
    ITEM_LIST_ACTION_76(0x76),
    UNIT_WEAR_ITEMS_ACTION_79(0x79),
    SACK_ACTION_7A(0x7A),
    BUILDING_HEALTH_ACTION_82(0x82),
    SHOW_SHOP_DIALOG_ACTION_83(0x83),
    SHOW_INN_DIALOG_ACTION_84(0x84),
    EFFECT_ACTION_86(0x86),
    AREA_EFFECT_ACTION_87(0x87),
    EFFECT_HANG_ACTION_88(0x88),
    EFFECT_GONE_ACTION_89(0x89),
    EFFECT_MULTI_TARGET_ACTION_8A(0x8A),
    EFFECT_FROM_ACTION_8B(0x8B),
    EFFECT_MULTI_FROM_ACTION_8C(0x8C),
    MESSAGE_ACTION_8D(0x8D),
    CHAT_TEXT_ACTION_91(0x91),
    GAME_EVENT_NOTIFICATION_ACTION_92(0x92),
    PLAYER_KICKED_ACTION_93(0x93),
    PLAYER_KILL_ANNOUNCEMENT_ACTION_94(0x94),
    NEW_PLAYER_ACTION_96(0x96),
    DELETE_PLAYER_ACTION_97(0x97),
    ASH_MAP_ACTION_98(0x98),
    TILE_VISIBILITY_MASK_ACTION_9B(0x9B),
    ENEMY_EQUIPMENT_ACTION_9C(0x9C),
    TWO_DWORD_ACTION_AA(0xAA),
    SET_CAMERA_POSITION_ACTION_AB(0xAB),
    TWO_DWORD_ACTION_AC(0xAC),
    TWO_DWORD_ACTION_AD(0xAD),
    SELECT_MULTIPLAYER_MAP_ACTION_AE(0xAE),
    SERVER_CLOSED_ACTION_AF(0xAF),
    PLAYER_KNOWLEDGE_PROGRESS_ACTION_B3(0xB3),
    MISSION_FAILED_ACTION_B4(0xB4),
    MISSION_COMPLETE_ACTION_B5(0xB5),
    QUEST_OBJECTIVES_QUERY_OPEN_ACTION_B6(0xB6),
    MISSION_STARTED_ACTION_B7(0xB7),
    RETURN_TO_LOBBY_ACTION_B8(0xB8),
    DIPLOMACY_ACTION_B9(0xB9),
    CREATURE_KNOWLEDGE_ACTION_BA(0xBA),
    PLAYER_QUESTS_ACTION_BB(0xBB),
    INN_QUESTS_ACTION_BC(0xBC),
    UPLOAD_CHARACTER_FILE_ACTION_BE(0xBE),
    MAP_CHECKSUM_ACTION_BF(0xBF),
    MAP_CHUNK_ACTION_C0(0xC0),
    LATENCY_SETTING_ACTION_C1(0xC1),
    MAP_TRANSFER_REDIRECT_ACTION_C2(0xC2),
    MAP_TRANSFER_TOKEN_ACTION_C3(0xC3),
    MAP_TRANSFER_SPOT_VISUAL_ACTION_C4(0xC4),
    MAP_TRANSFER_BUILDING_ACTION_C5(0xC5);

    public final int id;

    private static final Map<Integer, GameActionId> BY_ID = createById();

    // not ported.
    GameActionId(int id) {
        this.id = id;
    }

    // not ported.
    public static GameActionId fromId(int id) {
        return BY_ID.get(id);
    }

    // not ported.
    private static Map<Integer, GameActionId> createById() {
        Map<Integer, GameActionId> byId = new HashMap<>();
        for (GameActionId value : values()) {
            byId.putIfAbsent(value.id, value);
        }
        return byId;
    }
}
